output_dir: data/finetuned_models
checkpoints_dir: data/finetuned_models/checkpoints

preprocessor:
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet

dataset:
  class: GeneOntology
  path_df: "data/labeled_paths.csv"
  label_df: "data/terms.tsv"
  subontology: "MFO"
  sample: False
  split: [0.9, 0.05]

models:
  input_dim: 21
  hidden_dims: [512, 512, 512, 512, 512, 512]
  batch_norm: True
  concat_hidden: True
  short_cut: True
  readout: 'sum'
  num_relation: 7
  edge_input_dim: 59
  num_angle_bin: 8

task:
  weights_path: data/IA.txt
  criterion: bce
  num_mlp_layer: 3
  metric: ['auprc@micro', 'f1_max']

optimizer:
  class: AdamW
  lr: 1.0e-4
  weight_decay: 0

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0]
  batch_size: 1
  log_interval: 500
  gradient_interval: 4

model_checkpoint: {{ ckpt }}

metric: f1_max

verbose: True

train:
  num_epoch: 1