output_dir: ~/scratch/protein_output

preprocessor:
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet

task:
  class: WeightedMultipleBinaryClassification
  weights_path: data/IA.txt
  model:
    class: GearNet
    input_dim: 21
    hidden_dims: [512, 512, 512, 512, 512, 512]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    edge_input_dim: 59
    num_angle_bin: 8
  criterion: bce
  num_mlp_layer: 3
  metric: ['auprc@micro', 'f1_max']

optimizer:
  class: AdamW
  lr: 1.0e-4
  weight_decay: 0

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0]
  batch_size: 2
  log_interval: 10

model_checkpoint: {{ ckpt }}

metric: f1_max

train:
  num_epoch: 10